INSERT INTO Region (name) VALUES ('Europe');
INSERT INTO Country (regionID,name) VALUES (1,'Portugal');
INSERT INTO State(countryID,name) VALUES (1,'Lisboa');
INSERT INTO City(stateID,name) VALUES (1,'Lisbon');
INSERT INTO State(countryID,name) VALUES (1,'Porto');
INSERT INTO City(stateID,name) VALUES (2,'Picotos');
INSERT INTO State(countryID,name) VALUES (1,'Braga');
INSERT INTO City(stateID,name) VALUES (3,'Braga');
INSERT INTO State(countryID,name) VALUES (1,'Madeira');
INSERT INTO City(stateID,name) VALUES (4,'Funchal');
INSERT INTO State(countryID,name) VALUES (1,'Setúbal');
INSERT INTO City(stateID,name) VALUES (5,'Setúbal');
INSERT INTO State(countryID,name) VALUES (1,'Coimbra');
INSERT INTO City(stateID,name) VALUES (6,'Copeira');
INSERT INTO State(countryID,name) VALUES (1,'Azores');
INSERT INTO City(stateID,name) VALUES (7,'Ponta Delgada');
INSERT INTO State(countryID,name) VALUES (1,'Faro');
INSERT INTO City(stateID,name) VALUES (8,'Portimão');
INSERT INTO State(countryID,name) VALUES (1,'Évora');
INSERT INTO City(stateID,name) VALUES (9,'Évora');
INSERT INTO State(countryID,name) VALUES (1,'Aveiro');
INSERT INTO City(stateID,name) VALUES (10,'Aveiro');
INSERT INTO State(countryID,name) VALUES (1,'Leiria');
INSERT INTO City(stateID,name) VALUES (11,'Leiria');
INSERT INTO City(stateID,name) VALUES (8,'Faro');
INSERT INTO State(countryID,name) VALUES (1,'Beja');
INSERT INTO City(stateID,name) VALUES (12,'Beja');
INSERT INTO State(countryID,name) VALUES (1,'Bragança');
INSERT INTO City(stateID,name) VALUES (13,'Bragança');
INSERT INTO State(countryID,name) VALUES (1,'Castelo Branco');
INSERT INTO City(stateID,name) VALUES (14,'Castelo Branco');
INSERT INTO State(countryID,name) VALUES (1,'Guarda');
INSERT INTO City(stateID,name) VALUES (15,'Guarda');
INSERT INTO State(countryID,name) VALUES (1,'Santarém');
INSERT INTO City(stateID,name) VALUES (16,'Santarém');
INSERT INTO State(countryID,name) VALUES (1,'Viseu');
INSERT INTO City(stateID,name) VALUES (17,'Viseu');
INSERT INTO City(stateID,name) VALUES (14,'Covilhã');
INSERT INTO State(countryID,name) VALUES (1,'Vila Real');
INSERT INTO City(stateID,name) VALUES (18,'Vila Marim');
INSERT INTO State(countryID,name) VALUES (1,'Portalegre');
INSERT INTO City(stateID,name) VALUES (19,'Portalegre');
INSERT INTO State(countryID,name) VALUES (1,'Viana do Castelo');
INSERT INTO City(stateID,name) VALUES (20,'Viana do Castelo');
INSERT INTO City(stateID,name) VALUES (7,'Angra do Heroísmo');
INSERT INTO City(stateID,name) VALUES (7,'Portela');
INSERT INTO City(stateID,name) VALUES (8,'Lagos');
INSERT INTO City(stateID,name) VALUES (20,'Paredes de Coura');
INSERT INTO City(stateID,name) VALUES (17,'São João da Pesqueira');
INSERT INTO City(stateID,name) VALUES (10,'São João da Madeira');
INSERT INTO City(stateID,name) VALUES (15,'Fornos de Algodres');
INSERT INTO City(stateID,name) VALUES (10,'Castelo de Paiva');
INSERT INTO City(stateID,name) VALUES (9,'Portel');
INSERT INTO City(stateID,name) VALUES (2,'Porto');
INSERT INTO City(stateID,name) VALUES (14,'Sertã');
INSERT INTO City(stateID,name) VALUES (8,'Vila do Bispo');
INSERT INTO City(stateID,name) VALUES (19,'Fronteira');
INSERT INTO City(stateID,name) VALUES (13,'Alfândega da Fé');
INSERT INTO City(stateID,name) VALUES (15,'Celorico da Beira');
INSERT INTO City(stateID,name) VALUES (8,'Alcoutim');
INSERT INTO City(stateID,name) VALUES (19,'Arronches');
INSERT INTO City(stateID,name) VALUES (2,'Amarante');
INSERT INTO City(stateID,name) VALUES (17,'Tabuaço');
INSERT INTO City(stateID,name) VALUES (15,'Gouveia');
INSERT INTO City(stateID,name) VALUES (15,'Aguiar da Beira');
INSERT INTO City(stateID,name) VALUES (14,'Idanha-a-Nova');
INSERT INTO City(stateID,name) VALUES (18,'Ribeira de Pena');
INSERT INTO City(stateID,name) VALUES (15,'Seia');
INSERT INTO City(stateID,name) VALUES (16,'Rio Maior');
INSERT INTO City(stateID,name) VALUES (6,'Condeixa-a-Nova');
INSERT INTO City(stateID,name) VALUES (16,'Mação');
INSERT INTO City(stateID,name) VALUES (2,'Lousada');
INSERT INTO City(stateID,name) VALUES (15,'Trancoso');
INSERT INTO City(stateID,name) VALUES (10,'Estarreja');
INSERT INTO City(stateID,name) VALUES (5,'Moita');
INSERT INTO City(stateID,name) VALUES (20,'Ponte de Lima');
INSERT INTO City(stateID,name) VALUES (3,'Guimarães');
INSERT INTO City(stateID,name) VALUES (1,'Sobral de Monte Agraço');
INSERT INTO City(stateID,name) VALUES (5,'Seixal');
INSERT INTO City(stateID,name) VALUES (16,'Almeirim');
INSERT INTO City(stateID,name) VALUES (6,'Cantanhede');
INSERT INTO City(stateID,name) VALUES (19,'Elvas');
INSERT INTO City(stateID,name) VALUES (20,'Ponte da Barca');
INSERT INTO City(stateID,name) VALUES (16,'Golegã');
INSERT INTO City(stateID,name) VALUES (10,'Anadia');
INSERT INTO City(stateID,name) VALUES (12,'Moura');
INSERT INTO City(stateID,name) VALUES (19,'Avis');
INSERT INTO City(stateID,name) VALUES (10,'Águeda');
INSERT INTO City(stateID,name) VALUES (2,'Valongo');
INSERT INTO City(stateID,name) VALUES (20,'Caminha');
INSERT INTO City(stateID,name) VALUES (12,'Ourique');
INSERT INTO City(stateID,name) VALUES (16,'Sardoal');
INSERT INTO City(stateID,name) VALUES (2,'Vila do Conde');
INSERT INTO City(stateID,name) VALUES (18,'Alijó');
INSERT INTO City(stateID,name) VALUES (8,'Monchique');
INSERT INTO City(stateID,name) VALUES (3,'Cabeceiras de Basto');
INSERT INTO City(stateID,name) VALUES (8,'Aljezur');
INSERT INTO City(stateID,name) VALUES (11,'Castanheira de Pêra');
INSERT INTO City(stateID,name) VALUES (20,'Melgaço');
INSERT INTO City(stateID,name) VALUES (19,'Gavião');
INSERT INTO City(stateID,name) VALUES (19,'Monforte');
INSERT INTO City(stateID,name) VALUES (9,'Vila Viçosa');
INSERT INTO City(stateID,name) VALUES (12,'Almodôvar');
INSERT INTO City(stateID,name) VALUES (9,'Redondo');
INSERT INTO City(stateID,name) VALUES (20,'Vila Nova de Cerveira');
INSERT INTO City(stateID,name) VALUES (1,'Mafra');
INSERT INTO City(stateID,name) VALUES (6,'Lousã');
INSERT INTO City(stateID,name) VALUES (1,'Amadora');
INSERT INTO City(stateID,name) VALUES (15,'Pinhel');
INSERT INTO City(stateID,name) VALUES (9,'Estremoz');
INSERT INTO City(stateID,name) VALUES (14,'Penamacor');
INSERT INTO City(stateID,name) VALUES (17,'Penalva do Castelo');
INSERT INTO City(stateID,name) VALUES (19,'Crato');
INSERT INTO City(stateID,name) VALUES (17,'Nelas');
INSERT INTO City(stateID,name) VALUES (12,'Aljustrel');
INSERT INTO City(stateID,name) VALUES (3,'Esposende');
INSERT INTO City(stateID,name) VALUES (5,'Alcochete');
INSERT INTO City(stateID,name) VALUES (10,'Sever do Vouga');
INSERT INTO City(stateID,name) VALUES (5,'Sesimbra');
INSERT INTO City(stateID,name) VALUES (17,'São Pedro do Sul');
INSERT INTO City(stateID,name) VALUES (1,'Lourinhã');
INSERT INTO City(stateID,name) VALUES (17,'Santa Comba Dão');
INSERT INTO City(stateID,name) VALUES (16,'Entroncamento');
INSERT INTO City(stateID,name) VALUES (17,'Armamar');
INSERT INTO City(stateID,name) VALUES (20,'Arcos de Valdevez');
INSERT INTO City(stateID,name) VALUES (2,'Paços de Ferreira');
INSERT INTO City(stateID,name) VALUES (3,'Fafe');
INSERT INTO City(stateID,name) VALUES (19,'Ponte de Sôr');
INSERT INTO City(stateID,name) VALUES (17,'Moimenta da Beira');
INSERT INTO City(stateID,name) VALUES (18,'Santa Marta de Penaguião');
INSERT INTO City(stateID,name) VALUES (18,'Murça');
INSERT INTO City(stateID,name) VALUES (17,'Sernancelhe');
INSERT INTO City(stateID,name) VALUES (18,'Vila Real');
INSERT INTO City(stateID,name) VALUES (13,'Vinhais');
INSERT INTO City(stateID,name) VALUES (5,'Alcácer do Sal');
INSERT INTO City(stateID,name) VALUES (16,'Ourém');
INSERT INTO City(stateID,name) VALUES (2,'Vila Nova de Gaia');
INSERT INTO City(stateID,name) VALUES (19,'Castelo de Vide');
INSERT INTO City(stateID,name) VALUES (16,'Vila Nova da Barquinha');
INSERT INTO City(stateID,name) VALUES (8,'Loulé');
INSERT INTO City(stateID,name) VALUES (17,'Lamego');
INSERT INTO City(stateID,name) VALUES (11,'Alvaiázere');
INSERT INTO City(stateID,name) VALUES (17,'Sátão');
INSERT INTO City(stateID,name) VALUES (10,'Albergaria-a-Velha');
INSERT INTO City(stateID,name) VALUES (2,'Matosinhos');
INSERT INTO City(stateID,name) VALUES (9,'Alandroal');
INSERT INTO City(stateID,name) VALUES (14,'Proença-a-Nova');
INSERT INTO City(stateID,name) VALUES (8,'Lagoa');
INSERT INTO City(stateID,name) VALUES (5,'Montijo');
INSERT INTO City(stateID,name) VALUES (2,'Felgueiras');
INSERT INTO City(stateID,name) VALUES (11,'Nazaré');
INSERT INTO City(stateID,name) VALUES (6,'Miranda do Corvo');
INSERT INTO City(stateID,name) VALUES (17,'Penedono');
INSERT INTO City(stateID,name) VALUES (10,'Vale de Cambra');
INSERT INTO City(stateID,name) VALUES (13,'Vila Flor');
INSERT INTO City(stateID,name) VALUES (11,'Figueiró dos Vinhos');
INSERT INTO City(stateID,name) VALUES (5,'Santiago do Cacém');
INSERT INTO City(stateID,name) VALUES (2,'Trofa');
INSERT INTO City(stateID,name) VALUES (2,'Penafiel');
INSERT INTO City(stateID,name) VALUES (6,'Penacova');
INSERT INTO City(stateID,name) VALUES (11,'Pedrógão Grande');
INSERT INTO City(stateID,name) VALUES (14,'Oleiros');
INSERT INTO City(stateID,name) VALUES (19,'Sousel');
INSERT INTO City(stateID,name) VALUES (9,'Arraiolos');
INSERT INTO City(stateID,name) VALUES (6,'Poiares');
INSERT INTO City(stateID,name) VALUES (3,'Famalicão');
INSERT INTO City(stateID,name) VALUES (3,'Vila Verde');
INSERT INTO City(stateID,name) VALUES (3,'Terras de Bouro');
INSERT INTO City(stateID,name) VALUES (15,'Manteigas');
INSERT INTO City(stateID,name) VALUES (1,'Sintra');
INSERT INTO City(stateID,name) VALUES (3,'Vizela');
INSERT INTO City(stateID,name) VALUES (14,'Vila Velha de Ródão');
INSERT INTO City(stateID,name) VALUES (16,'Benavente');
INSERT INTO City(stateID,name) VALUES (2,'Maia');
INSERT INTO City(stateID,name) VALUES (2,'Santo Tirso');
INSERT INTO City(stateID,name) VALUES (1,'Oeiras');
INSERT INTO City(stateID,name) VALUES (3,'Celorico de Basto');
INSERT INTO City(stateID,name) VALUES (11,'Bombarral');
INSERT INTO City(stateID,name) VALUES (5,'Barreiro');
INSERT INTO City(stateID,name) VALUES (14,'Belmonte');
INSERT INTO City(stateID,name) VALUES (6,'Montemor-o-Velho');
INSERT INTO City(stateID,name) VALUES (10,'Espinho');
INSERT INTO City(stateID,name) VALUES (6,'Oliveira do Hospital');
INSERT INTO City(stateID,name) VALUES (17,'Oliveira de Frades');
INSERT INTO City(stateID,name) VALUES (10,'Oliveira de Azemeis');
INSERT INTO City(stateID,name) VALUES (10,'Oliveira do Bairro');
INSERT INTO City(stateID,name) VALUES (9,'Viana do Alentejo');
INSERT INTO City(stateID,name) VALUES (13,'Carrazeda de Anciães');
INSERT INTO City(stateID,name) VALUES (10,'Ovar');
INSERT INTO City(stateID,name) VALUES (16,'Torres Novas');
INSERT INTO City(stateID,name) VALUES (1,'Torres Vedras');
INSERT INTO City(stateID,name) VALUES (16,'Cartaxo');
INSERT INTO City(stateID,name) VALUES (17,'Mangualde');
INSERT INTO City(stateID,name) VALUES (17,'Vila Nova de Paiva');
INSERT INTO City(stateID,name) VALUES (2,'Paredes');
INSERT INTO City(stateID,name) VALUES (12,'Vidigueira');
INSERT INTO City(stateID,name) VALUES (16,'Chamusca');
INSERT INTO City(stateID,name) VALUES (3,'Trofa');
INSERT INTO City(stateID,name) VALUES (13,'Macedo de Cavaleiros');
INSERT INTO City(stateID,name) VALUES (17,'Resende');
INSERT INTO City(stateID,name) VALUES (3,'Póvoa de Lanhoso');
INSERT INTO City(stateID,name) VALUES (10,'Feira');
INSERT INTO City(stateID,name) VALUES (1,'Azambuja');
INSERT INTO City(stateID,name) VALUES (3,'Vieira do Minho');
INSERT INTO City(stateID,name) VALUES (11,'Batalha');
INSERT INTO City(stateID,name) VALUES (16,'Alcanena');
INSERT INTO City(stateID,name) VALUES (5,'Palmela');
INSERT INTO City(stateID,name) VALUES (16,'Ferreira do Zêzere');
INSERT INTO City(stateID,name) VALUES (10,'Arouca');
INSERT INTO City(stateID,name) VALUES (14,'Vila de Rei');
INSERT INTO City(stateID,name) VALUES (16,'Tomar');
INSERT INTO City(stateID,name) VALUES (17,'Tondela');
INSERT INTO City(stateID,name) VALUES (16,'Constância');
INSERT INTO City(stateID,name) VALUES (18,'Vila Pouca de Aguiar');
INSERT INTO City(stateID,name) VALUES (5,'Almada');
INSERT INTO City(stateID,name) VALUES (15,'Almeida');
INSERT INTO City(stateID,name) VALUES (12,'Alvito');
INSERT INTO City(stateID,name) VALUES (6,'Soure');
INSERT INTO City(stateID,name) VALUES (1,'Alenquer');
INSERT INTO City(stateID,name) VALUES (12,'Mértola');
INSERT INTO City(stateID,name) VALUES (18,'Mesão Frio');
INSERT INTO City(stateID,name) VALUES (9,'Mourão');
INSERT INTO City(stateID,name) VALUES (18,'Valpaços');
INSERT INTO City(stateID,name) VALUES (11,'Pombal');
INSERT INTO City(stateID,name) VALUES (13,'Mogadouro');
INSERT INTO City(stateID,name) VALUES (2,'Póvoa de Varzim');
INSERT INTO City(stateID,name) VALUES (2,'Baião');
INSERT INTO City(stateID,name) VALUES (17,'Mortágua');
INSERT INTO City(stateID,name) VALUES (6,'Tábua');
INSERT INTO City(stateID,name) VALUES (1,'Cascais');
INSERT INTO City(stateID,name) VALUES (3,'Barcelos');
INSERT INTO City(stateID,name) VALUES (18,'Boticas');
INSERT INTO City(stateID,name) VALUES (18,'Sabrosa');
INSERT INTO City(stateID,name) VALUES (18,'Montalegre');
INSERT INTO City(stateID,name) VALUES (2,'Gondomar');
INSERT INTO City(stateID,name) VALUES (13,'Freixo de Espada à Cinta');
INSERT INTO City(stateID,name) VALUES (9,'Mora');
INSERT INTO City(stateID,name) VALUES (9,'Vendas Novas');
INSERT INTO City(stateID,name) VALUES (15,'Vila Nova de Foz Côa');
INSERT INTO City(stateID,name) VALUES (11,'Caldas da Rainha');
INSERT INTO City(stateID,name) VALUES (19,'Marvão');
INSERT INTO City(stateID,name) VALUES (13,'Vimioso');
INSERT INTO City(stateID,name) VALUES (1,'Odivelas');
INSERT INTO City(stateID,name) VALUES (12,'Odemira');
INSERT INTO City(stateID,name) VALUES (11,'Peniche');
INSERT INTO City(stateID,name) VALUES (10,'Vagos');
INSERT INTO City(stateID,name) VALUES (2,'Marco de Canavezes');
INSERT INTO City(stateID,name) VALUES (16,'Coruche');
INSERT INTO City(stateID,name) VALUES (6,'Coimbra');
INSERT INTO City(stateID,name) VALUES (12,'Barrancos');
INSERT INTO City(stateID,name) VALUES (9,'Montemor-o-Novo');
INSERT INTO City(stateID,name) VALUES (15,'Mêda');
INSERT INTO City(stateID,name) VALUES (11,'Óbidos');
INSERT INTO City(stateID,name) VALUES (6,'Góis');
INSERT INTO City(stateID,name) VALUES (9,'Reguengos de Monsaraz');
INSERT INTO City(stateID,name) VALUES (13,'Torre de Moncorvo');
INSERT INTO City(stateID,name) VALUES (10,'Murtosa');
INSERT INTO City(stateID,name) VALUES (11,'Alcobaça');
INSERT INTO City(stateID,name) VALUES (6,'Figueira da Foz');
INSERT INTO City(stateID,name) VALUES (15,'Figueira de Castelo Rodrigo');
INSERT INTO City(stateID,name) VALUES (16,'Abrantes');
INSERT INTO City(stateID,name) VALUES (1,'Arruda dos Vinhos');
INSERT INTO City(stateID,name) VALUES (14,'Fundão');
INSERT INTO City(stateID,name) VALUES (17,'Tarouca');
INSERT INTO City(stateID,name) VALUES (10,'Ílhavo');
INSERT INTO City(stateID,name) VALUES (16,'Alpiarça');
INSERT INTO City(stateID,name) VALUES (8,'Albufeira');
INSERT INTO City(stateID,name) VALUES (6,'Penela');
INSERT INTO City(stateID,name) VALUES (20,'Valença');
INSERT INTO City(stateID,name) VALUES (3,'Amares');
INSERT INTO City(stateID,name) VALUES (8,'São Brás de Alportel');
INSERT INTO City(stateID,name) VALUES (6,'Pampilhosa da Serra');
INSERT INTO City(stateID,name) VALUES (8,'Tavira');
INSERT INTO City(stateID,name) VALUES (19,'Nisa');
INSERT INTO City(stateID,name) VALUES (19,'Alter do Chão');
INSERT INTO City(stateID,name) VALUES (12,'Castro Verde');
INSERT INTO City(stateID,name) VALUES (10,'Mealhada');
INSERT INTO City(stateID,name) VALUES (12,'Cuba');
INSERT INTO City(stateID,name) VALUES (17,'Vouzela');
INSERT INTO City(stateID,name) VALUES (1,'Vila Franca de Xira');
INSERT INTO City(stateID,name) VALUES (11,'Marinha Grande');
INSERT INTO City(stateID,name) VALUES (17,'Cinfães');
INSERT INTO City(stateID,name) VALUES (9,'Borba');
INSERT INTO City(stateID,name) VALUES (6,'Mira');
INSERT INTO City(stateID,name) VALUES (8,'Silves');
INSERT INTO City(stateID,name) VALUES (5,'Grândola');
INSERT INTO City(stateID,name) VALUES (19,'Campo Maior');
INSERT INTO City(stateID,name) VALUES (12,'Ferreira do Alentejo');
INSERT INTO City(stateID,name) VALUES (13,'Miranda do Douro');
INSERT INTO City(stateID,name) VALUES (13,'Mirandela');
INSERT INTO City(stateID,name) VALUES (18,'Chaves');
INSERT INTO City(stateID,name) VALUES (5,'Sines');
INSERT INTO City(stateID,name) VALUES (18,'Mondim de Basto');
INSERT INTO City(stateID,name) VALUES (20,'Monção');
INSERT INTO City(stateID,name) VALUES (8,'Castro Marim');
INSERT INTO City(stateID,name) VALUES (17,'Castro Daire');
INSERT INTO City(stateID,name) VALUES (6,'Arganil');
INSERT INTO City(stateID,name) VALUES (8,'Olhão');
INSERT INTO City(stateID,name) VALUES (1,'Cadaval');
INSERT INTO City(stateID,name) VALUES (1,'Loures');
INSERT INTO City(stateID,name) VALUES (16,'Salvaterra de Magos');
INSERT INTO City(stateID,name) VALUES (18,'Peso da Régua');
INSERT INTO City(stateID,name) VALUES (12,'Serpa');
INSERT INTO City(stateID,name) VALUES (15,'Sabugal');
INSERT INTO City(stateID,name) VALUES (11,'Ansião');
INSERT INTO City(stateID,name) VALUES (8,'Vila Real de Santo António');
INSERT INTO City(stateID,name) VALUES (11,'Porto de Mós');
